{% extends ./src/templates/layout/index.phtml %}

{% block title %}Artigos{% endblock %}
{% block description %}Conteúdos sobre desenvolvimento de software em todo lugar!{% endblock %}

{% block content %}
<style>
    body {
        max-width: 100%;         
    }
    header nav {
        margin: 0 auto;
        max-width: 750px;
    }
    header h1 {
        margin: 0 auto;
        max-width: 750px;
    }
</style>
<div style="display: flex; flex-wrap: wrap; justify-content: center">
    {% foreach ($posts as $post): %}
        <section class="item">
            <img class="center" src="/images/{{$post['image']}}" />
            <h3>{{ $post['title'] }}</h3>
            <p>{{ explode(".", $post['description'])[0] }}...</p>
            <div style="flex: 1"></div>
            <a style="align-self: flex-start" href='{{ $GLOBALS['static']['url_prefix'] }}posts/{{$post['slug']}}'>{{ $GLOBALS['static']['keep_reading'] }}</a>
        </section>
    {% endforeach; %}
</div>
    
{% endblock %}