{% extends ./src/templates/layout/manager.phtml %}

{% block title %}Manager - Novo layout{% endblock %}

{% block content %}

<a href=/manager/layouts>Voltar</a>
<form method=post class=flex>
    <label for=name>Nome</label>
    <input name=name />
    <label for=content>Conteúdo</label>
    <div class="editor language-html" id="content-editor"></div>
    <input id="content-input" type="hidden" name="content" />
    <button>Enviar</button>
</form>
<script type="module">
    import {CodeJar} from '/js/codejar.js';
    let jar = CodeJar(document.querySelector('#content-editor'), Prism.highlightElement, {tab: '    '})
    let contentInput = document.querySelector('#content-input');
    jar.onUpdate(code => {
        contentInput.value = code;
    });
</script>
{% endblock %}