{% extends ./src/templates/layout/manager.phtml %}

{% block title %}Manager - Edit template{% endblock %}

{% block content %}
<a href=/manager/templates>Voltar</a>
<form method=post class=flex>
    <label for=name>Name</label>
    <input name=name value={{$template['name']}} disabled />
    <label for=content>Content</label>
    <div class="editor language-html" id="content-editor"></div>
    <input id="content-input" type="hidden" name="content" value="{{{$template['content']}}}" />
    <button>Enviar</button>
</form>

<script type="module">
    import {CodeJar} from '/js/codejar.js';
    let jar = CodeJar(document.querySelector('#content-editor'), Prism.highlightElement, {tab: '    '})
    let contentInput = document.querySelector('#content-input');
    jar.updateCode(contentInput.value);
    jar.onUpdate(code => {
        contentInput.value = code;
    });
</script>
{% endblock %}